### ISSUE TITLE
Searching for a work via title

### ISSUE THREAD

**Issue by Wrench-wench** [ArmindoFlores/ao3_api#16]
When searching for a work via it's title the search results return as something I don't understand.
Searching the code doesn't reveal anything about how the results are returned or supposed to be understood.

```import AO3

search_result = AO3.Search(title="The Real Meaning of Idioms")
search_result.update()
print(search_result)
```
Returns this result in the terminal:
<AO3.search.Search object at 0x7f5ab4ea6100>

I did at first thing this was due to a title collision but have tested this will multiple titles.

**Comment by ArmindoFlores** [comment]
The correct usage should be
```py3
search_result = AO3.Search(title="The Real Meaning of Idioms")
search_result.update()
print(search_result)
```

which gets you this result:
```
[<Work [The Real Meaning of Idioms]>, <Work [[PODFIC] The Real Meaning of Idioms]>, <Work [Cover for The Real Meaning of Idioms]>]
```

**Comment by Wrench-wench** [comment]
Thank you for the response, would you have a suggested way of getting the workID or URL from a title?

**Comment by ArmindoFlores** [comment]
I don't think there's really a way around searching and selecting one of the results. After you have them, you can use something like `search_result.results[0].workid` to get the ID of the first one.

**Comment by Wrench-wench** [comment]
It's close enough to what I need.
Cheers!
