### ISSUE TITLE
When is_subscribed is called for a Series object, an AttributeError is returned 

### ISSUE THREAD

**Issue by Aspect1103** [ArmindoFlores/ao3_api#28]
So if is_subscribed is called for a Series object, the following error is returned:
`form = self._soup.find("form", {"data-create-value": "Subscribe"})
AttributeError: 'NoneType' object has no attribute 'find'`

However, its gets even weirder as it still returns the correct value (True if the user is subscribed to a series and False if they aren't).

Maybe you could shed some light on why this is.

**Comment by ArmindoFlores** [comment]
Can you send me the series ID or name? I can't seem to replicate it.

**Comment by Aspect1103** [comment]
So I tried it with both a restricted work and a non-restricted work. Seems like it comes up if you grab all the series from a specific work and then iterate over each one calling is_subscribed. The code for a non-restricted series

`work = AO3.Work(AO3.utils.workid_from_url("https://archiveofourown.org/works/5463839"), ao3Session)

for series in work.series:
    print(series.is_subscribed)`

For a restricted series, you can use https://archiveofourown.org/series/1209360.

Creating a new Series object on each iteration and using that seems to solve it. May just be a problem with the authentication/session object.

**Comment by ArmindoFlores** [comment]
The `Series` objects returned after calling `work.series` are not loaded (I don't think that's actually written anywhere), therefore you need to call `series.reload()` to access some of the information.

**Comment by ArmindoFlores** [comment]
This is the code for `work.series`

```python
@cached_property
def series(self):
    """Returns the series this work belongs to"""
    
    from .series import Series
    dd = self._soup.find("dd", {"class": "series"})
    if dd is None:
        return []
    
    s = []
    for span in dd.find_all("span", {"class": "position"}):
        seriesid = int(span.a.attrs["href"].split("/")[-1])
        seriesname = span.a.getText()
        series = Series(seriesid, self._session, False)  #! The load parameter is set to False
        setattr(series, "name", seriesname)
        s.append(series)
    return s
```

You can see in the line ` series = Series(seriesid, self._session, False)` where we instantiate the Series object that we also set the load parameter to False

**Comment by Aspect1103** [comment]
Ahhh, didn't know they weren't loaded. That about solves it then. Thanks.
