### ISSUE TITLE
Unable to install package on repl.it.

### ISSUE THREAD

**Issue by enigmalea** [ArmindoFlores/ao3_api#29]
I'm unable to install your API on repl.it. After some searching it seems that the issue might be due to an outdated python library. Is there any way you can update it?

Here is the actual error I'm receiving:

```
--> python3 -m poetry add ao3-api
Using version ^2.0.6 for ao3-api

Updating dependencies
Resolving dependencies...

[AssertionError]

exit status 1


Repl.it: Package operation failed.
```

**Comment by ArmindoFlores** [comment]
Could you provide some additional information? I was able to install it with no problems on repl.it

![a](https://user-images.githubusercontent.com/40968362/107894902-292ba300-6f29-11eb-98d0-d0ddf10a12c9.png)

**Comment by enigmalea** [comment]
Thanks for the reply. I think it might have been conflicting somehow with the discord.py package I was using. I was able to install it on a fresh repl.it. I'm going to try with a new discord library.
