### ISSUE TITLE
series.work_list not pulling

### ISSUE THREAD

**Issue by enigmalea** [ArmindoFlores/ao3_api#32]
I'm not sure what happened, but series.work_list is returning a blank object. It was working fine a couple of weeks ago, but I was working on my bot and noticed that it's returning blank lists. I checked it with a couple of different series, and even checked it without manipulating the data. 

![image](https://user-images.githubusercontent.com/73132777/111385025-96de0280-8680-11eb-9449-611e95434c5e.png)

![image](https://user-images.githubusercontent.com/73132777/111385073-a3625b00-8680-11eb-813c-75cb8909ab79.png)

**Comment by jvicens** [comment]
Hello,

It happens something similar to me. I'm doing a search() getting that the total results are consistent with the same search in the website. However, the results are empty.

<img width="496" alt="Screenshot 2021-03-18 at 13 43 59" src="https://user-images.githubusercontent.com/5405396/111628050-0f170600-87f0-11eb-9d8a-9c9aaa25dfc0.png">
<img width="496" alt="Screenshot 2021-03-18 at 13 44 09" src="https://user-images.githubusercontent.com/5405396/111628052-10483300-87f0-11eb-8852-a474b55b82ea.png">

Thanks!

**Comment by ArmindoFlores** [comment]
Something might have changed on the website, I've verified it on my computer so I'll check this out

**Comment by Aspect1103** [comment]
I think AO3 changed their code a bit. Replacing the following lines in the work_list() function fixed it for me:
`for work in ul.find_all("li", {'class': 'work blurb group'}):`
To:
`for work in ul.find_all("li", {'role': 'article'}):`

**Comment by jvicens** [comment]
Thank you! This solves the problem with the work list.

> `for work in ul.find_all("li", {'role': 'article'}):`

**Comment by th555** [comment]
To fix the issue with search, the same replacement can be done [here](https://github.com/ArmindoFlores/ao3_api/blob/07278edc6cb3991c249cf934e3678e7bd9580de4/AO3/search.py#L88).
