### ISSUE TITLE
work.metadata not working

### ISSUE THREAD

**Issue by enigmalea** [ArmindoFlores/ao3_api#33]
I was trying to pull info from work.metadata and was getting no response. I took a look at the source code in the 2.0.7 release package and it looks like work.metadata and updates associated with it aren't present, even though your release notes state that it was included in the update. Just wanted to let you know.

**Comment by ArmindoFlores** [comment]
I checked both the source code and the binaries in [v2.0.7](https://github.com/ArmindoFlores/ao3_api/releases/tag/v2.0.7) and in pypi and both have the work.metadata property. Can you provide some more info?

**Comment by enigmalea** [comment]
I pulled the code from the zip file here and either can't type for the find feature or something. So I just looked again and I DO see it, but it's not returning anything when I run it.

![image](https://user-images.githubusercontent.com/73132777/111662197-1afdca80-87e6-11eb-9313-c6e4f7cad1b6.png)

![image](https://user-images.githubusercontent.com/73132777/111662294-2c46d700-87e6-11eb-932c-1eda3c06d059.png)

Output is a bit odd because I'm working with a live discord bot. The last line is the "keep awake" script executing. But you can see above that, it prints the work id, work title, work authors just fine and then just _nothing_.

**Comment by enigmalea** [comment]
well now I am thoroughly confused. Let me play around with it outside of the bot coding for a bit and I'll see what happens.

**Comment by enigmalea** [comment]
I started with a fresh repl.it outside of my bot framework It looks like metadata is working, but expected chapters, complete, and status are not.
![image](https://user-images.githubusercontent.com/73132777/111687717-fc58fd00-8800-11eb-92ba-1cb38c2fdf3b.png)

![image](https://user-images.githubusercontent.com/73132777/111687907-3cb87b00-8801-11eb-968f-036dbbf8020a.png)

![image](https://user-images.githubusercontent.com/73132777/111687942-48a43d00-8801-11eb-8368-08671484a912.png)


It was difficult to tell with that hot mess of a fic with all the data ever so I tried with one with less data and it appears those fields aren't populating inside of the metadata output either.
![image](https://user-images.githubusercontent.com/73132777/111688594-9b7df480-8801-11eb-87f2-b323fe46e1e4.png)

work.metadata still isn't working within the framework of the bot, but that could be a me issue.

**Comment by enigmalea** [comment]
Also, for what it's worth, I thought the issue might also be because the first fic I tried was unknown chapters, but the second is 1/1 and complete, so that doesn't seem to be it either.

**Comment by ArmindoFlores** [comment]
Alright, I'll look at it again more in depth when I have the time. Thanks for the input

**Comment by ArmindoFlores** [comment]
What is the version you're using?

**Comment by enigmalea** [comment]
So repl.it is claiming that it's 2.0.7 that's installed, but I'm starting to think it's reading the correct version number from PyPi, but not actually installing the correct package.

![image](https://user-images.githubusercontent.com/73132777/113511415-a0df7c80-952d-11eb-8827-93b961864f01.png)

**Comment by ArmindoFlores** [comment]
Maybe try
```python
import AO3
print(AO3.VERSION)
```

**Comment by enigmalea** [comment]
It's showing 2.0.7, but still not working for those particular attributes. I started with a fresh repl.it and reinstalled. There must be some sort of error between PyPi and Repl.it. I can try sending a ticket to Repl.it as well if the PyPi upload should be supporting those attributes.

![image](https://user-images.githubusercontent.com/73132777/113643325-0deb3300-9650-11eb-8134-50955ae63d31.png)

**Comment by ArmindoFlores** [comment]
This is totally my fault. I forgot those changes hadn't yet been published to PyPi. They should be in version 2.0.8. Sorry for the inconvenience.
