### ISSUE TITLE
Work Won't Load

### ISSUE THREAD

**Issue by enigmalea** [ArmindoFlores/ao3_api#34]
While using my discord bot someone found a work that just fails to load for some reason that I haven't been able to work out. The screenshot below shows another work successfully loading, and then the one which one load right afterward.

This was the link to the work that fails: https://archiveofourown.org/works/22833073/

![image](https://user-images.githubusercontent.com/73132777/113490092-097b1a80-9496-11eb-9d38-9eba798c825e.png)

**Comment by ArmindoFlores** [comment]
Can you check your `AO3.VERSION`? I tried it and I can pull the data from that work

**Comment by enigmalea** [comment]
This may  have been a weird repl.it thing. I uninstalled and reinstalled the package (which was showing version 2.0.7 before and after install) and it works this morning.
