### ISSUE TITLE
Pull chapter data?

### ISSUE THREAD

**Issue by manavortex** [ArmindoFlores/ao3_api#36]
Hey there, 

do you think you could provide an endpoint that allows accessing the chapter data? As in, chapter title, summary, #words...? :) That would be grand!

Thank you.

**Comment by ArmindoFlores** [comment]
I'm working on it 😁

**Comment by ArmindoFlores** [comment]
I implemented some changes on works.py and added chapters.py. You might to to check them out! The basic gist is:
```py3
import AO3
work = AO3.Work(29433366)
print("First 2 chapters:", work.chapters[:2])
print("\n"+work.chapters[1].start_notes)
print(work.chapters[2].words)
```
```
First 2 chapters: [<Chapter [Valentine's Day (1)] from [<Work [Home Free]>]>, <Chapter [First Date (2)] from [<Work [Home Free]>]>]

Thank you so much to everyone who commented and kudos'ed on the first chapter! I'm glad you enjoyed the beginning, first chapters are always hard for me, and this one got just a weeee bit more of the side of existential angst than I intended, haha!
This is fluffier fare! Kinda. I think. Hope.
(See the end of the chapter for  more notes.)

1179
```

Alternatively, you can start with a chapter ID and go from there:

```py3
import AO3

chapter = AO3.Chapter(72374859, None)
print(chapter.work)
print(chapter in chapter.work.chapters)
```

```
<Work [Home Free]>
True
```

Although I would be careful with this latter use because I don't think my implementation is very robust.

**Comment by ArmindoFlores** [comment]
Also, be aware that this is not on version 2.0.8, and the only way you'll get access to these changes is by cloning the repository.

**Comment by manavortex** [comment]
Awesome, thank you!

**Comment by ArmindoFlores** [comment]
> Awesome, thank you!
Do let me know if you find any major issues
