### ISSUE TITLE
Work.subscribe() isn't working

### ISSUE THREAD

**Issue by ArmindoFlores** [ArmindoFlores/ao3_api#39]
Work.subscribe() isn't working and throws an AuthError instead

**Comment by SamthonyStar** [comment]
Hello, first of all, thank you for all your work! Yours is the first python library I'm working with and I'm learning a lot. With that said, I'm still getting an AuthError when using work.subscribe(), even though I can log into the session properly and retrieve things, like my subscriptions, from my profile.

**Comment by ArmindoFlores** [comment]
Are you using the version from PyPi or did you clone the repo?

**Comment by SamthonyStar** [comment]
I'm using the version from PyPi

**Comment by ArmindoFlores** [comment]
It's not fixed on PyPi yet. If you want the fix you're going to have to clone this repo and install via setup.py, or download from the releases tab and use the wheel file (.whl) to install with pip.
