### ISSUE TITLE
Incomplete works with one chapter are considered oneshots

### ISSUE THREAD

**Issue by tze-min** [ArmindoFlores/ao3_api#42]
I'm not sure if it was intended to be this way, but shouldn't the `oneshot` property of a work return true if it has one chapter and is considered complete? Currently, it only accounts for the former condition, but this means multichaptered fics that's only got one chapter for now are counted as oneshots as well.

**Comment by ArmindoFlores** [comment]
This was intentional. However, if people think it would make more sense for it to work a different way, I'm open to changing it.

**Comment by tze-min** [comment]
I see, thanks!! I'd be good with either.
