### ISSUE TITLE
Search results is empty

### ISSUE THREAD

**Issue by popaconsta** [ArmindoFlores/ao3_api#44]
I have run a code snippet in a Jupyter Notebook without any issues, and it's still working. However, when I put the same code in a .py script, and try to run it, the search _results_ field is empty after every query, no matter the page number. What am I doing wrong? 

`{'any_field': '', 'title': '', 'author': '', 'single_chapter': False, 'word_count': None, 'language': '', 'fandoms': 'Harry Potter - J. K. Rowling', 'rating': None, 'hits': None, 'bookmarks': None, 'comments': None, 'completion_status': None, 'page': 4, 'sort_column': '', 'sort_direction': '', 'results': [], 'pages': 14906, 'total_results': 298119}`

**Comment by ArmindoFlores** [comment]
Perhaps you're using a different version of the package on Jupyter and when you run the script. Can you try to `print(AO3.VERSION)`?

**Comment by popaconsta** [comment]
Oops, you're absolutely right, I had an older version running with the script. Thank you!
