### ISSUE TITLE
AttributeError: 'Work' object has no attribute 'workid'

### ISSUE THREAD

**Issue by Wrench-wench** [ArmindoFlores/ao3_api#45]
After running a search, attempting to get the workid of a work from search results page fails.

Here is the code (simple.py), normally this should print the workid of the first result of the search results page.
```python
# Written in Python 3.8.5 64-bit, tested on Ubuntu Desktop 20.04.02 LTS.
import AO3

print('AO3.VERSION is:', AO3.VERSION)
search_results = AO3.Search(word_count=AO3.utils.Constraint(5000, 15000000),fandoms="Supernatural", language="en")
search_results.update()

workid = search_results.results[0].workid
print(workid)
```
Here is the output:
```python
~$ python3 simple.py
AO3.VERSION is: 2.1.0
Traceback (most recent call last):
  File "simple.py", line 17, in <module>
    workid = search_results.results[0].workid
AttributeError: 'Work' object has no attribute 'workid'
```
I also tried this with an older script that I know had worked previously (AO3.VERSION:  2.0.3) which also fails with the same error message if I run this same file. 
The code in this file is just ripped out a previous working file so I suspect there has been some change on the ArchiveOfOurOwn website search results that has caused this.
Given the timing I think #44 is probably affected by this.

**Comment by ArmindoFlores** [comment]
I may have forgotten to document this change. `Work.workid` is now `Work.id`. This applies to Series, Comments, Chapters, etc...
[See here](https://github.com/ArmindoFlores/ao3_api/blob/master/AO3/works.py)

**Comment by Wrench-wench** [comment]
Awesome, cheers!
