### ISSUE TITLE
from bs4 import BeautifulSoup

### ISSUE THREAD

**Issue by Wrench-wench** [ArmindoFlores/ao3_api#5]
Several files require BeautifulSoup (search.py, users.py, series.py, extra.py, session.py, comments.py, utils.py and works.py) but it's not installed or listed as a requirement by ao3_api either on GitHub or PyPI.

Should this be listed as requirement in the README or included as part of the PyPI install?

**Comment by Wrench-wench** [comment]
Installing BeautifulSoup4 via ```pip install --upgrade bs4``` and running the first snippet from the README returns the work ID but not the chapters.

The error message is ```bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested lxml. Do you need to install a parser library?```

To solve this install lxml via ```pip install --upgrade lxml`` and it should start working correctly

**Comment by ArmindoFlores** [comment]
> Several files require BeautifulSoup (search.py, users.py, series.py, extra.py, session.py, comments.py, utils.py and works.py) but it's not installed or listed as a requirement by ao3_api either on GitHub or PyPI.
> 
> Should this be listed as requirement in the README or included as part of the PyPI install?

I'm not sure why that didn't install with pip. BeautifulSoup and lxml and both listed as a requirement on setup.py. 
![Dependencies](https://imgur.com/H9PLAt2.jpg)

**Comment by Wrench-wench** [comment]
Found what went wrong:
Hadn't ran ```python3 setup.py install```

This should probably be added to the README
