### ISSUE TITLE
Search.update() fails if a work's word count is blank

### ISSUE THREAD

**Issue by Prill** [ArmindoFlores/ao3_api#52]
Specifically, if it comes across a fic with a blank word count (`<dd class="words"></dd>`) it throws a ValueError because `''` can't be cast to an integer. Should be a fairly minor fix.

An example of a fic: https://archiveofourown.org/works/27776251. It appears to be some weird bug in Ao3 itself, and the fic was later reposted by the same author but has all the attributes.

**Comment by ArmindoFlores** [comment]
Sorry for taking so long, I somehow forgot about his issue
