### ISSUE TITLE
Creating bookmarks

### ISSUE THREAD

**Issue by sparsityc** [ArmindoFlores/ao3_api#54]
Thank you for your work on this library!
Since there is a function to leave kudos, is it possible to make one for creating bookmarks?

**Comment by ArmindoFlores** [comment]
I don't see why it wouldn't! I'm very busy at the moment, so I won't be able to add it for a while, but feel free to do so and submit a pull request

**Comment by ArmindoFlores** [comment]
This feature was added on 16e867827679607b3a36627746a76b84070ce679
