### ISSUE TITLE
get_images returning KeyError due to AO3 source

### ISSUE THREAD

**Issue by enigmalea** [ArmindoFlores/ao3_api#55]
Depending on how authors are adding images and what AO3 is doing with that, I'm running into a few works which return a KeyError because there is a blank img tag with no src defined.

![image](https://user-images.githubusercontent.com/73132777/124681332-450ef180-de96-11eb-94e0-4cfc842a79ff.png)

(For reference the above code is from [here](https://archiveofourown.org/works/28566909))

Is there a way you can have chapters.get_images exclude blank img tags so other images are still retrievable?

**Comment by ArmindoFlores** [comment]
Thanks for letting me know of this bug!
