### ISSUE TITLE
Error if there are no series bookmarks

### ISSUE THREAD

**Issue by searchtools-avi** [ArmindoFlores/ao3_api#56]
This is an obscure case and very frustrating, in the latest 2.2.0 version.  

If there are no bookmarks for a series, the label is not there either

```
<dt class="stats">Stats:</dt>
<dd class="stats">
<dl class="stats">
<dt>Words:</dt>
<dd>23,327</dd>
<dt>Works:</dt>
<dd>16</dd>
<dt>Complete:</dt>
<dd>No</dd>
</dl>
</dd>
</dl>
```
So when I ask for **series.nbookmarks** it returns this error: `UnboundLocalError: local variable 'book' referenced before assignment`

I tried to work around it, but my try... except Exception handling doesn't get the error very well, nor does hasattr(series, 'nbookmarks').  Could you fix this, preferably by returning 0?

Thanks

**Comment by searchtools-avi** [comment]
testable series: 1638784

**Comment by ArmindoFlores** [comment]
There's probably a couple more fields with this issue, I'm gonna do some more testing
