### ISSUE TITLE
ImportError: No module named ao3

### ISSUE THREAD

**Issue by lovelightwings** [ArmindoFlores/ao3_api#68]
Wondering why I'm not able to import the library on VSCode or any online IDE. Still a beginner so maybe it's an obvious issue I'm missing. 
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/85091020/155861423-347ab030-09fc-4876-98b5-43c7af5ff8f7.png">

**Comment by ArmindoFlores** [comment]
Did you download it first? I don't usually use online IDEs but I imagine you'd have to install it first, did you do so?

**Comment by lovelightwings** [comment]
Yeah! This isn't the full thing but currently I have 2 AO3 related libraries installed because of the project I'm working on. Tried `import AO3
from AO3 import AO3
from ao3-api import AO3`
and other combinations of the like, but nada :( 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/85091020/155892580-2ad9e44b-fc08-46f0-9744-89fec01ae6c7.png">

**Comment by ArmindoFlores** [comment]
Please send me an email so we can discuss this further, since this isn't really an issue with tha package itself.
