### ISSUE TITLE
Increase ability to interact with collections

### ISSUE THREAD

**Issue by LordGiacomoS** [ArmindoFlores/ao3_api#69]
When I was searching for an API for AO3, I was specifically looking for something that could be used to help sort through hundreds of private bookmarks in order to build a collection of public recommendations to share with others. Unfortunately, with the current limits of this API, it looks like I can only add bookmarks to collections rather than invite works to them, meaning I'd have to manually add each work.

Any chance you plan to make/are working on something that allows me to add/invite works to collections based on workid?

**Comment by ArmindoFlores** [comment]
I haven't had much experience with collections - thus the lack of tools for interacting with them through ao3-api - but I do plan on adding more functionality regarding them. Of course, I would also encourage you to contribute to the project by submitting a pull request with the added functionality should you get around to writing it.

**Comment by LordGiacomoS** [comment]
Wrote some basic functionality to address this concern at https://github.com/ArmindoFlores/ao3_api/pull/70
